{% set version = "0.12.7" %}

package:
  name: pycrdt-websocket
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt-websocket/pycrdt_websocket-{{ version }}.tar.gz
  sha256: 5ce1d3ad8ba5d3407400f3dcf5d96c9b9d9836fb421928ac5698dd094ed18cfa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - aiosqlite >=0.18.0,<1
    - pycrdt >=0.8.7,<0.9.0
    - anyio >=3.6.2,<5

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
    - uvicorn
  imports:
    - pycrdt_websocket
  commands:
    - pip check
    - cd tests && npm install
    - cd .. && pytest -vv --asyncio-mode=auto --cov-branch --cov=pycrdt_websocket --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=69

about:
  home: https://github.com/jupyter-server/pycrdt-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for pycrdt
  doc_url: https://davidbrochart.github.io/pycrdt-websocket

extra:
  recipe-maintainers:
    - davidbrochart
