{% set version = "0.15.5" %}

package:
  name: pycrdt-websocket
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycrdt-websocket/pycrdt_websocket-{{ version }}.tar.gz
  sha256: aff8c07693ab43b98102ccdaf421738c7d0893db376815de824ea4b4e533de7e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=3.6.2,<5
    - sqlite-anyio >=0.2.3,<0.3.0
    - pycrdt >=0.10.3,<0.13.0

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-cov
    - httpx-ws >=0.5.2
    - hypercorn
    - trio >=0.25.0
    - sniffio
    - python {{ python_min }}
  imports:
    - pycrdt_websocket
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/pycrdt-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for pycrdt
  doc_url: https://davidbrochart.github.io/pycrdt-websocket

extra:
  recipe-maintainers:
    - davidbrochart
