{% set version = "0.15.1" %}

package:
  name: pycrdt-websocket
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pycrdt-websocket/pycrdt_websocket-{{ version }}.tar.gz
  sha256: a20b6c6c4926c57176c23bdaee79b064297c50acd251b55f29c7a9ee7068a6c8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - anyio >=3.6.2,<5
    - sqlite-anyio >=0.2.1,<0.3.0
    - pycrdt >=0.10.1,<0.11.0

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-cov
    - httpx-ws >=0.5.2
    - hypercorn
    - trio >=0.25.0
    - sniffio
  imports:
    - pycrdt_websocket
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/pycrdt-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for pycrdt
  doc_url: https://davidbrochart.github.io/pycrdt-websocket

extra:
  recipe-maintainers:
    - davidbrochart
